---
kind: pipeline
type: kubernetes
name: hello-world

steps:
- name: deploy-mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: atomi_exp
    MYSQL_USER: appuser
    MYSQL_PASSWORD: p6FGFvLcQ2sm
  detach: true

- name: deploy-firebase
  image: spine3/firebase-emulator
  environment:
    GCP_PROJECT: "quickstart-123456"
    ENABLE_UI: "true"
  detach: true

- name: build-and-run-atomi
  image: golang:1.20
  environment:
    GIT_USERNAME: admin-atomi
    GIT_TOKEN:
      from_secret: github_token
  commands:
    - apt update && apt install -y netcat
    - git clone https://$GIT_USERNAME:$GIT_TOKEN@github.com/${DRONE_REPO_OWNER}/atomi.git
    - cd atomi
    - go mod vendor
    - go build ./exp/init_db
    - go build .
    - ../test_driver/wait-for-port.sh 127.0.0.1 3306
    - ../test_driver/wait-for-port.sh 127.0.0.1 9099
    - CONFIG_FILE=.config/testing.yaml ./init_db
    - CONFIG_FILE=.config/testing.yaml ./atomi
  detach: true

- name: main
  image: ghcr.io/cirruslabs/flutter:3.7.9
  commands:
    - apt update && apt install -y netcat
    - flutter pub get
    - ./test_driver/wait-for-port.sh 127.0.0.1 9099
    - ./test_driver/wait-for-port.sh 127.0.0.1 8081
    - flutter test test/src/provider/user_provider_test.dart
