name: fryo
description: A food ordering app template kit.

version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.7.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: '^2.0.9'
  flutter_rating_bar: ^4.0.1
  firebase_core: '^2.9.0'
  firebase_auth: '^4.4.0'
  google_sign_in: '^6.0.2'
  http: '^0.13.5'
  cupertino_icons: '^1.0.5'
  provider: ^6.0.1
  flutter_stripe: ^9.0.0+1
  logging: ^1.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # TODO(lamuguo): 本地图片只用于app的渲染，不应与product / store的定制化相关。下面的数字图像应该都要删掉。
  # To add assets to your application, add an assets section, like this:
  assets:
   - images/welcome.png
   - images/1.png
   - images/2.png
   - images/3.png
   - images/4.png
   - images/5.png
   - images/6.png
   - images/7.png
   - images/8.png
   - images/9.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Fryo
      fonts:
        - asset: fonts/Fryo.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
