// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE6QLDoquG2-rvvJX5C4cTjbwY49-VdCg',
    appId: '1:194699638421:web:843ae3c34fe8672a5dcd9c',
    messagingSenderId: '194699638421',
    projectId: 'quickstart-1589068586497',
    authDomain: 'quickstart-1589068586497.firebaseapp.com',
    storageBucket: 'quickstart-1589068586497.appspot.com',
    measurementId: 'G-R6QR4LS7X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ9_LRdrRCLGsYtLh8rqW4Yb5aZtCEa5Q',
    appId: '1:194699638421:android:5468232c7abc2ceb5dcd9c',
    messagingSenderId: '194699638421',
    projectId: 'quickstart-1589068586497',
    storageBucket: 'quickstart-1589068586497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFjwmOkcqA0Dsi7eyGPT9M6U-IGbhEiNA',
    appId: '1:194699638421:ios:163c65664934e0c95dcd9c',
    messagingSenderId: '194699638421',
    projectId: 'quickstart-1589068586497',
    storageBucket: 'quickstart-1589068586497.appspot.com',
    iosClientId: '194699638421-sof24sph0bakbpp17tes5qo1h3rpbs20.apps.googleusercontent.com',
    iosBundleId: 'ai.atomi.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFjwmOkcqA0Dsi7eyGPT9M6U-IGbhEiNA',
    appId: '1:194699638421:ios:163c65664934e0c95dcd9c',
    messagingSenderId: '194699638421',
    projectId: 'quickstart-1589068586497',
    storageBucket: 'quickstart-1589068586497.appspot.com',
    iosClientId: '194699638421-sof24sph0bakbpp17tes5qo1h3rpbs20.apps.googleusercontent.com',
    iosBundleId: 'ai.atomi.grocery',
  );
}
